### ISSUE TITLE
Unsoundness in moveit::ctor::[try_]assign

### ISSUE THREAD

**Issue by coolreader18** [google/moveit#7]
```rust
>> use std::pin::Pin;
>> let mut pinned = Box::pin(Box::new(123));
>> moveit::ctor::try_assign(pinned.as_mut(), moveit::ctor::from_try_fn(|| Err(())))
Err(())
>> let b: Box<i32> = *Pin::into_inner(pinned);
>> b
-1594092836
>> b
-1594092772
>> b
-1594092836
```
Essentially, `[try_]assign` doesn't guarantee that `lvalue` won't be accessible if the ctor panics or (in `TryCtor`'s case) returns an Err, so we can access `lvalue.deref_mut()` even after `ptr::drop_in_place` was called on it.

**Comment by mcy** [comment]
Hmm. Best I can think of is this (analogous for `try_assign`):
```rust
```

**Comment by mcy** [comment]
After thinking about this really hard my conclusion is that `assign` is unfixable, and that's fine because C++ does not provide a functionality like it anyway. The closest you can get is
```cpp
template <typename T, typename... Args>
void Assign(T& dest, Args&&... args) {
  dest.~T();
  new (&dest) T(std::forward(args)...);
}
```
Just like in Rust, if `T::T()` throws, you lose. I think that the correct solution is:
- Get rid of `assign`, since it's unfixable. (I'll close the issue once I do that.)
- Model move/copy assignment as the following traits, which mirror the definition of `operator=` in C++:
```rust
trait CopyFrom {  // Basically just Clone.
  fn copy_from(&self, src: &Self); 
}
trait MoveFrom {
  fn move_from(self: Pin<&mut Self>, src: &mut Self);
}
```
(Some appropriate amount of `unsafe` needs to be sprinkled on.)
